export default {
  textTitleMain: '3rem',
  textTitleBanner: '3rem',
  textTitleSection: '2.2rem',
  textTitleParagraph: '2rem',
  textTitleCard: '2rem',
  textSubtitleCard: '1.8rem',
  textSmallSubtitle: '1.7rem',
  textPCard: '1.6rem',
  textSmallP: '1.3rem',
  textSmallTitle: '1.5rem',
  textCard: '1.4rem',
  textSmallCard: '1.2rem',
  textCart: '2.2rem',
  textStep: '2rem',
  textBtn: '1.8rem',
  textBtnNext: '1.7rem',
  textBtnPwa: '1.7rem',
  textBtnCount: '2rem',
  textBtnCard: '1.6rem',
  textLabel: '1.5rem',
  textFloatLabel: '1.2rem',
  textInput: '1.5rem',
  textError: '1.2rem'
}
