import dynamic from 'next/dynamic'

export { Footer } from 'components/Footer'
export { Header } from 'components/Header'
export { HeadPage } from 'components/HeadPage'
export { TitleSection } from 'components/TitleSection'
export const CardsSquare = dynamic(() => import('components/CardsSquare'))
export { BtnNext } from 'components/BtnNext'
export { Additional } from 'components/Additional'
export { Cart } from 'components/Cart'
export { Steps } from 'components/Steps'
export { Flavor } from 'components/Flavor'
export { Size } from 'components/Size'
export { Toast, NotifyError, NotifySuccess } from 'components/Toast'
export { FormData } from 'components/Forms/FormData'
export { Input } from 'components/Forms/Input'
export { Select } from 'components/Forms/Select'
export { Banner } from 'components/Banner'
export { PopupInstallPwa } from 'components/PopupInstallPwa'
export { CookieWarning } from 'components/CookieWarning'
export { ContainerCardControlRender } from 'components/ContainerCardControlRender'
